spring:
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false